### PR TITLE
(client) Fixed SVG background

### PR DESCRIPTION
**Pull request by slashtechno**
Fixed the SVG background. The problem I found was that instead of the complete SVG code inside the HTML file, it ended with `... (32 KB left)`. I replaced the embedded SVG code with an image tag which points to the SVG file. In my opinion, this also makes the code easier to read.

EDIT: Also, I am aware there was no person in the original image. However, when I went to UnDraw to get the original SVG, I was unable to remove the person from the image. An alternative solution would be to keep the original SVG code, and add it to a file rather than keeping it in the code.

### CODE REVIEW

**Comment by slashtechno** [comment]
I tried to correct an earlier commit with git reset, (git ammend may
have been better). When I tired to correct it, I learned that the
original, deleted commit worked better. Thus, I am re-commiting that
previous commit.

**Comment by Glitch752** [comment]
Yes, the person being removed was intentional. It is, however, a good idea to move the SVG to another file. If you don't want to modify the SVG, I would be willing to do so.

**Comment by slashtechno** [comment]
> Yes, the person being removed was intentional. It is, however, a good idea to move the SVG to another file. If you don't want to modify the SVG, I would be willing to do so.

I attempted to modify the SVG using GIMP. The SVG seems to be seen as one part in GIMP. If you can remove the person from the image, go ahead.

**Comment by Glitch752** [comment]
Fixed in #5e35c04.

**Pull request closed without merging**
